#!/bin/zsh

# Zsh Configuration Files
_RC_DIR="$HOME/.config/zsh"
source "$_RC_DIR/alias"
source "$_RC_DIR/history"
source "$_RC_DIR/utils"

# Functions Configuration
_RC_FUNC_DIR="$_RC_DIR/functions"
source "$_RC_FUNC_DIR/docker"
source "$_RC_FUNC_DIR/utils"