#!/bin/zsh

# Remove the current directory
rmcu () {
	local current_dir="$PWD"
	local parent_dir="$(dirname "$current_dir")"
	cd "$parent_dir" || {
		echo "Error: Failed to change directory to '$parent_dir'." >&2
		return 1
	}
	command rm -rf "$current_dir"
}
