name: Build

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
      with:
        path: dotfiles
        submodules: recursive

    - name: Monitor Workflow Performance
      uses: ke-kawai/workflow-performance-monitor@v1.0.0

    - name: Move repository to HOME directory
      run: |
        mv dotfiles $HOME/dotfiles

    - name: Run setup
      run: |
        cd $HOME/dotfiles
        make setup
      shell: zsh {0}

    - name: Run ls to verify dotfiles
      run: |
        ls -la $HOME/.zshrc $HOME/.vimrc $HOME/.gitconfig $HOME/.nvm
        ls -laR $HOME/.config
      shell: zsh {0}
    
    - name: Run cleanup
      run: |
        cd $HOME/dotfiles
        make clean
      shell: zsh {0}
