name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: dotfiles
        submodules: recursive

    - name: Move repository to HOME directory
      run: |
        mv dotfiles $HOME/dotfiles

    - name: Run setup
      run: make setup
      working-directory: ${{ env.HOME }}/dotfiles
      shell: zsh {0}

    - name: Run ls to verify dotfiles
      run: ls -laR $HOME
      shell: zsh {0}
    
    - name: Run cleanup
      run: make clean
      working-directory: ${{ env.HOME }}/dotfiles
      shell: zsh {0}
